@file:Suppress("SpellCheckingInspection")

package com.ilittle7.router.utils

/**
 * register setting
 */
object ScanSetting {
    const val DOT_CLASS = ".class"

    /**
     * The register code is generated into this class
     */
    const val GENERATE_TO_CLASS_NAME = "com/ilittle7/router/transform/ActualRouterManager"

    /**
     * you know. this is the class file(or entry in jar file) name
     */
    const val GENERATE_TO_CLASS_FILE_NAME = "$GENERATE_TO_CLASS_NAME$DOT_CLASS"

    /**
     * The register code is generated into this method
     */
    const val GENERATE_TO_METHOD_NAME = "loadAll"

    /**
     * The package name of the class generated by the annotationProcessor
     */
    const val ROUTER_CLASS_PACKAGE_NAME = "com/ilittle7/router/gen/RouterManager_"

    /**
     * register method name in class: {@link #GENERATE_TO_CLASS_NAME}
     */
    const val REGISTER_METHOD_NAME = "register"
}